### ISSUE TITLE
Add schema validation to anyconfig data

### ISSUE THREAD

**Issue by Grokzen** [dynamist/phabfive#26]
### Environment
* Phabfive version: latest
* Python version: 3.x

### Proposed Functionality

Add json schema validation to the internal data/config that is using anyconfig to build the config file based on files on disk.

https://python-anyconfig.readthedocs.io/en/latest/usage.html#validation-with-and-or-generate-json-schema

An example/WIP schema.yaml:

```
type: object
properties:
  PHABFIVE_DEBUG: {type: boolean}
  PHAB_TOKEN: {type: string}
  PHAB_URL: {type: string}
```

### Use Case

None

### Other?

None
